config/routes.rb
Rails.application.routes.draw do

  devise_for :user
  get 'home/index'
  root 'home#index'

  resources :admins
  resources :groups do
    resources :group_timetables
  end

  resources :users
  resources :timetables, only: [:index, :show, :edit, :update]

end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :parent, class_name: "Group"

  has_many :children, class_name: "Group", dependent: :destroy

  has_and_belongs_to_many :users
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
  before_create :create_items

  belongs_to :user

  has_many :items, class_name: "TimetableItem", dependent: :destroy

  def get_ordered_items
    items.order :name
  end

  private

    def create_items
      ['1', '2', '3', '4', '5'].each do |day|
        items << TimetableItem.create(timetable_id: id, name: day)
      end
    end
end

app/models/timetable_item.rb
class TimetableItem < ActiveRecord::Base
  belongs_to :timetable

  def get_array
    [first, second, third, fourth, fifth]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  belongs_to :timetable

  has_and_belongs_to_many :groups

  def administrator?
    groups.find_by(category: 'administrator').present?
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authority_check

  def index
  end

  private

    def authority_check
      unless current_user.administrator?
        redirect_to root_path, notice: t('notice.authority')
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :group_id

    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/group_timetables_controller.rb
class GroupTimetablesController < ApplicationController
  before_action :init_timetable, only: [:index]

  def index
    @group = Group.find(params[:group_id])
    @group.users.each do |user|
      if user.timetable.present?
        user.timetable.get_ordered_items.each_with_index do |user_item, y|
          user_item.get_array.each_with_index do |flag, x|
            @timetable[y][x] = @timetable[y][x] || flag
          end
        end
      end
    end
  end

  private

    def init_timetable
      @timetable = []
      5.times do
        @timetable << [false, false, false, false, false]
      end
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authority_check, only: [:new, :edit, :create, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    if current_user.administrator?
      @groups = Group.all
    else
      @groups = Group.where.not(category: 'administrator')
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @users = User.all
  end

  # GET /groups/1/edit
  def edit
    @users = User.all
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: t('notice.groups.create') }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: t('notice.groups.update') }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: t('notice.groups.delete') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :category, :user_ids => []).merge(deletable: true)
    end

    def authority_check
      unless current_user.administrator?
        redirect_to root_path, notice: t('notice.authority')
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :load_timetable, only: [:index]
  before_action :set_timetable, only: [:show, :edit, :update]

  def index
  end

  # GET /timetables/1
  # GET /timetables/1.json
  def show
  end

  # GET /timetables/1/edit
  def edit
  end

  # PATCH/PUT /timetables/1
  # PATCH/PUT /timetables/1.json
  def update
    timetable_params.each do |param|
      item = @timetable.items.find(param[0])
      param[1].each do |idx|
        item[idx.to_s] = true
      end
      item.save
    end

    respond_to do |format|
        format.html { redirect_to @timetable, notice: t('notice.timetable.update') }
        format.json { render :show, status: :ok, location: @timetable }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetable
      @timetable = Timetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetable_params
      params.require(:items)
    end

    def load_timetable
      #timetable = Timetable.find_by(user_id: current_user.id)

      unless current_user.timetable.present?
        current_user.timetable = Timetable.create(user_id: current_user.id)
        current_user.save
      end

      redirect_to timetable_path(current_user.timetable)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authority_check, only: [:index, :new, :edit, :create, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @groups = Group.all
  end

  def show
  end

  def edit
    @groups = Group.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: t('notice.users.create')
    else
      redirect_to @user.errors, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('notice.users.update')
    else
      redirect_to @user.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: t('notice.users.delete')
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :group_ids => [])
    end

    def authority_check
      unless current_user.administrator?
        redirect_to root_path, notice: t('notice.authority')
      end
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_timetables_helper.rb
module GroupTimetablesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/index.html.erb
<h1><%= t('admin_page.title') %></h1>

<ul>
  <li><%= link_to t('admin_page.groups'), groups_path %></li>
  <li><%= link_to t('admin_page.users'), users_path %></li>
</ul>

app/views/group_timetables/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @group.name + t('group_timetable.title')%></h1>

<table>
  <tr>
    <td><%= t('timetable.classes') %></td>
    <td><%= t('timetable.monday') %></td>
    <td><%= t('timetable.tuesday') %></td>
    <td><%= t('timetable.wednesday') %></td>
    <td><%= t('timetable.thursday') %></td>
    <td><%= t('timetable.friday') %></td>
  </tr>

  <% @timetable.each_with_index do |item, idx| %>
    <tr>
      <td><%= idx + 1 %></td>
      <% item.each do |flag| %>
        <td><%= flag ? 'o' : '' %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('groups.name') %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label t('groups.category') %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label t('groups.user') %><br>
    <% @users.each do |user| %>
      <%= check_box_tag 'group[user_ids][]', user.id, checked=@group.users.exists?(id: user.id), id: "user_#{user.id}" %> <%= user.name %><br />
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit t('groups.decide') %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1><%= t('groups.edit') %></h1>

<%= render 'form' %>

<%= link_to t('groups.show'), @group %> |
<%= link_to t('groups.back'), groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('groups.title') %></h1>

<table>
  <tr>
    <td><strong><%= t('groups.name') %></strong></td>
    <td><strong><%= t('groups.category') %></strong></td>
  </tr>

  <% @groups.each do |group| %>
    <tr>
      <td><%= link_to group.name, group %></td>
      <td><%= group.category %></td>
      <td><%= link_to t('groups.timetable'), group_group_timetables_path(group) %></td>

      <% if current_user.administrator? %>
        <% if group.deletable %>
          <td><%= link_to t('groups.edit'), edit_group_path(group) %></td>
          <td><%= link_to t('groups.destroy'), group, method: :delete, data: { confirm: '削除しますか?' } %></td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
</table>

<br>

<% if current_user.administrator? %>
  <%= link_to t('groups.new'), new_group_path %>
<% end %>

app/views/groups/new.html.erb
<h1><%= t('groups.new') %></h1>

<%= render 'form' %>

<%= link_to t('groups.back'), groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('groups.show') %></h1>

<p>
  <strong><%= t('groups.name') %>:</strong>
  <%= @group.name %>
</p>

<p>
  <strong><%= t('groups.category') %>:</strong>
  <%= @group.category %>
</p>

<div>
  <strong><%= t('groups.user') %></strong><br />
  <ul>
  <% @group.users.each do |user| %>
    <li><%= user.name %> : <%= user.email %></li>
  <% end %>
  </ul>
</div>

<% if current_user.administrator? %>
  <%= link_to t('groups.edit'), edit_group_path(@group) %> |
<% end %>
<%= link_to t('groups.back'), groups_path %>

app/views/home/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('mypage.title') %></h1>
<% if user_signed_in? %>
  <%= t('mypage.message') %> <strong><%= current_user.name %></strong> さん <br /><br />
<% else %>
  <%= link_to t('devise.labels.sign_up'), new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to t('devise.labels.login'), new_user_session_path, :class => 'navbar-link' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "B5GWS" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href=<%= root_path %>><%= t('twitter.navbar.top') %></a>
        <div class="nav-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <% if user_signed_in? %>
            <div class="well sidebar-nav">
              <h3><%= t('twitter.sidebar.title') %></h3>
              <ul class="nav nav-list">
                <% if current_user.administrator? %>
                  <li><%= link_to t('twitter.sidebar.admin'), admins_path, :class => "navbar-link"  %></li>
                <% end %>
                <li><%= link_to t('twitter.sidebar.group_show'), groups_path, :class => "navbar-link"  %></li>
                <li><%= link_to t('twitter.sidebar.timetable_show'), timetables_path, :class => "navbar-link"  %></li>
                <li><%= link_to t('twitter.sidebar.show'), user_path(current_user), :class => "navbar-link"  %></li>
                <li><%= link_to t('twitter.sidebar.setting'), edit_user_registration_path, :class => "navbar-link"  %></li>
                <li><%= link_to t('twitter.sidebar.logout'), destroy_user_session_path, method: :delete, :class => "navbar-link"  %></li>
              </ul>
            </div><!--/.well -->
          <% end %>
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/timetables/_form.html.erb
<%= form_for(@timetable) do |f| %>
  <% if @timetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timetable.errors.count, "error") %> prohibited this timetable from being saved:</h2>

      <ul>
      <% @timetable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= t('timetable.classes') %></td>
      <td><%= t('timetable.monday') %></td>
      <td><%= t('timetable.tuesday') %></td>
      <td><%= t('timetable.wednesday') %></td>
      <td><%= t('timetable.thursday') %></td>
      <td><%= t('timetable.friday') %></td>
    </tr>

    <% @timetable.get_ordered_items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= check_box_tag 'items[' + item.id.to_s + '][]', :first, item.first %></td>
        <td><%= check_box_tag 'items[' + item.id.to_s + '][]', :second, item.second %></td>
        <td><%= check_box_tag 'items[' + item.id.to_s + '][]', :third, item.third %></td>
        <td><%= check_box_tag 'items[' + item.id.to_s + '][]', :fourth, item.fourth %></td>
        <td><%= check_box_tag 'items[' + item.id.to_s + '][]', :fifth, item.fifth %></td>
      </tr>
    <% end %>
  </table>

  <div class="actions">
    <%= f.submit t('timetable.update') %>
  </div>
<% end %>

app/views/timetables/edit.html.erb
<h1><%= t('timetable.edit_title') %></h1>

<%= render 'form' %>

<%= link_to t('timetable.back'), @timetable %>

app/views/timetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('timetable.user_name') %>:</strong>
  <%= @timetable.user.name %>
</p>

<table>
  <tr>
    <td><%= t('timetable.classes') %></td>
    <td><%= t('timetable.monday') %></td>
    <td><%= t('timetable.tuesday') %></td>
    <td><%= t('timetable.wednesday') %></td>
    <td><%= t('timetable.thursday') %></td>
    <td><%= t('timetable.friday') %></td>
  </tr>

  <% @timetable.get_ordered_items.each do |item| %>
    <tr>
      <td><%= item.name %></td>
      <td><%= item.first ? 'o' : '' %></td>
      <td><%= item.second ? 'o' : '' %></td>
      <td><%= item.third ? 'o' : '' %></td>
      <td><%= item.fourth ? 'o' : '' %></td>
      <td><%= item.fifth ? 'o' : '' %></td>
    </tr>
  <% end %>
</table>

<%= link_to t('timetable.edit'), edit_timetable_path(@timetable) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('users.name') %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label t('users.email') %><br>
    <%= f.text_field :email %>
  </div>

  <% if controller.action_name == "new" %>
    <div class="field">
      <%= f.label t('devise.labels.password') %> <br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>
    <div class="field">
      <%= f.label t('devise.labels.password_confirm') %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('users.groups') %><br>
    <% @groups.each do |group| %>
      <%= check_box_tag 'user[group_ids][]', group.id, checked=@user.groups.exists?(id: group.id), id: "group_#{group.id}" %> <%= group.name %><br />
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit t('users.create') %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('users.edit_title') %></h1>

<%= render 'form' %>

<%= link_to t('users.show'), @user %> |
<%= link_to t('users.back'), users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('users.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('users.name') %></th>
      <th><%= t('users.email') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= link_to t('users.edit'), edit_user_path(user.id) %></td>
        <td><%= link_to t('users.destroy'), user_path(user.id), method: :delete, data: { confirm: '削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('users.new'), new_user_path %>

app/views/users/new.html.erb
<h1><%= t('users.new') %></h1>

<%= render 'form' %>

<%= link_to t('users.back'), users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('users.show') %></h1>

<p>
  <strong><%= t('users.name') %>:</strong>
  <%= @user.name %>
</p>

<p>
  <strong><%= t('users.email') %>:</strong>
  <%= @user.email %>
</p>

<div>
  <strong><%= t('users.groups') %></strong><br />
  <ul>
  <% @user.groups.each do |group| %>
    <li><%= group.name %></li>
  <% end %>
  </ul>
</div>

<% if current_user.administrator? %>
  <%= link_to t('users.edit'), edit_user_path(@user) %> |
  <%= link_to t('users.back'), users_path %>
<% else %>
  <%= link_to t('users.edit'), edit_user_registration_path, :class => "navbar-link" %>
<% end %>